FROM node:20-bullseye-slim

RUN mkdir /usr/app

RUN mkdir /usr/app/node_modules

WORKDIR /usr/app

COPY package.json ./

COPY tsconfig.json ./

COPY drizzle.config.ts ./

COPY planetscale.configuration.ts ./

COPY src ./src

RUN npm install nodemon -g

EXPOSE 3000

CMD [ "npm", "run","dev"]